In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor

In [2]:
df = pd.read_csv('regression.csv')
df

age  experience  income
0    25           1   30450
1    30           3   35670
2    47           2   31580
3    32           5   40130
4    43          10   47830
5    51           7   41630
6    28           5   41340
7    33           4   37650
8    37           5   40250
9    39           8   45150
10   29           1   27840
11   47           9   46110
12   54           5   36720
13   51           4   34800
14   44          12   51300
15   41           6   38900
16   58          17   63600
17   23           1   30870
18   44           9   44190
19   37          10   48700

In [38]:
x = df.iloc[:, 0:-1]
x

age  experience
0    25           1
1    30           3
2    47           2
3    32           5
4    43          10
5    51           7
6    28           5
7    33           4
8    37           5
9    39           8
10   29           1
11   47           9
12   54           5
13   51           4
14   44          12
15   41           6
16   58          17
17   23           1
18   44           9
19   37          10

In [39]:
y = df['income']
y

0     30450
1     35670
2     31580
3     40130
4     47830
5     41630
6     41340
7     37650
8     40250
9     45150
10    27840
11    46110
12    36720
13    34800
14    51300
15    38900
16    63600
17    30870
18    44190
19    48700
Name: income, dtype: int64

In [40]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=42)

In [41]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((16, 2), (16,), (4, 2), (4,))

In [42]:
knn = KNeighborsRegressor(n_neighbors=5)
knn

KNeighborsRegressor()

In [43]:
knn.fit(x_train, y_train)

KNeighborsRegressor()

In [44]:
knn.predict([[1.0, 0.7]])

C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([37442.])

In [45]:
y_pred = knn.predict(x_test)
y_pred

array([37442., 37442., 45224., 37442.])

In [46]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [47]:
print(f'Mean Squared Error: {mean_squared_error(y_test, y_pred)}')
print(f'Mean Absolute Error: {mean_absolute_error(y_test, y_pred)}')

Mean Squared Error: 33803052.0
Mean Absolute Error: 5415.0


In [48]:
x_test

age  experience
0    25           1
17   23           1
15   41           6
1    30           3

In [49]:
x_train

age  experience
8    37           5
5    51           7
11   47           9
3    32           5
18   44           9
16   58          17
13   51           4
2    47           2
9    39           8
19   37          10
4    43          10
12   54           5
7    33           4
10   29           1
14   44          12
6    28           5

In [50]:
y_test

0     30450
17    30870
15    38900
1     35670
Name: income, dtype: int64

In [51]:
y_pred

array([37442., 37442., 45224., 37442.])